### ISSUE TITLE
1.2.1 导出html的格式有误

### ISSUE THREAD

**Issue by nahso** [foxsen/archbase#13]
原文为：冒泡排序算法的运算复杂度为O(N\*N)，快速排序算法的运算复杂度为O(N\*log2(N))

在html版本中，两个 \* 中间的文本被解释为了斜体，而且*号也没有显示出来，建议加个转义或者直接嵌latex $O(N^2)$

**Comment by foxsen** [comment]
感谢，确实应该加转义。类似的问题12章也存在
