### ISSUE TITLE
请问有习题的参考答案吗？

### ISSUE THREAD

**Issue by wanghuibin0** [foxsen/archbase#19]
不知道去哪问，就冒昧在这问了：请问有习题的参考答案吗？

**Comment by foxsen** [comment]
目前已有部分答案其他在完善中。为了避免同学偷懒，不打算直接公开答案。教师们可以和我们联系获取。

**Comment by wanghuibin0** [comment]
> 目前已有部分答案其他在完善中。为了避免同学偷懒，不打算直接公开答案。教师们可以和我们联系获取。

好的，明白

**Comment by lhcezx** [comment]
> 目前已有部分答案其他在完善中。为了避免同学偷懒，不打算直接公开答案。教师们可以和我们联系获取。

作者您好，想要和您这边联系取得相关习题答案，想请问下咱们的联系方式是？
