### ISSUE TITLE
建议： 基于龙芯的工作流

### ISSUE THREAD

**Issue by cheungxi** [foxsen/archbase#21]
建议Dockerfile,  ci, cd 都能基于龙芯处理器（mips / la)

我在mips 上安装tinytex 失败

所以直接用的apt源里的 `texlive-full`

但是`make pdf` 时提示 bookdown.tex
667行 `\textbackslash{}providecommand\{\textbackslash{}docline\}{[}3{]}\{\noalign{\global\setlength{\arrayrulewidth}{#1}}\arrayrulecolor[HTML]{#2}\cline{#3}\}`  ` ! Misplaced \noalign`

但是编译bookdown的demo工程， `bookdown-demo` 是可以无错通过的。

**Comment by foxsen** [comment]
CD是github提供的，没得选，除非自己搭服务器。龙芯上编译的问题回头我抽空看看。Latex的诡异问题很多，可能是版本差异导致的，我在ubuntu 20.04上用texlive 2020/2021编译过，后来为了缩小CD镜像的大小才改用tinytex。

**Comment by cheungxi** [comment]
> 建议Dockerfile, ci, cd 都能基于龙芯处理器（mips / la)
> 
> 我在mips 上安装tinytex 失败
> 
> 所以直接用的apt源里的 `texlive-full`
> 
> 但是`make pdf` 时提示 bookdown.tex 667行 `\textbackslash{}providecommand\{\textbackslash{}docline\}{[}3{]}\{\noalign{\global\setlength{\arrayrulewidth}{#1}}\arrayrulecolor[HTML]{#2}\cline{#3}\}` ` ! Misplaced \noalign`
> 
> 但是编译bookdown的demo工程， `bookdown-demo` 是可以无错通过的。

` ! Misplaced \noalign` 可能也是 flextable 的问题引起的

**Comment by foxsen** [comment]
暂不修复
