### ISSUE TITLE
图9.11 PC时钟周期问题

### ISSUE THREAD

**Issue by ruxiliang** [foxsen/archbase#25]
<img width="739" alt="image" src="https://user-images.githubusercontent.com/91934643/146883628-94acd337-2945-47e9-8f3b-e5355fd23fe7.png">

如上图，在第六个时钟周期的时候，此时刚好等完I0指令写回寄存器，I1指令解除阻塞，R1端正式译码从寄存器堆中把数据读出来，然后I2取出地址。

问题在于，在第七个时钟周期的时候，I2和I3也存在RAW的依赖，所以I2指令也要阻塞。可此时I2的PC已经取出，第七个时钟周期按教材讲授以及图9.10均可发现第七个时钟周期，I3在执行PC指令，而9.11却显示第七个时钟周期是I2在执行PC，请问是不是图画错了？

**Comment by foxsen** [comment]
确实是图错了，应该是I3
