### ISSUE TITLE
编辑问题-在线HTML版本。

### ISSUE THREAD

**Issue by berwincc** [foxsen/archbase#26]
在线HTML版本https://foxsen.github.io/archbase

[在9.5.3转移预测中](https://foxsen.github.io/archbase/%E6%8C%87%E4%BB%A4%E6%B5%81%E6%B0%B4%E7%BA%BF.html#sec-branch-predict)，

可以通过寄存器重命名变为：
div.w   $r3,$r2,$r1
add.w   $r5,$r4,$r3
sub.w   $r3,$r7,$r6
mul.w   $r9,$r8,$r3

pdf 版本中此处内容为：

可以通过寄存器重命名变为: 
div.w $r3, $r2, $r1
add.w $r5, $r4, $r3
sub.w  $r10, $r7, $r6
mul.w $r9, $r8, $r10

**Comment by foxsen** [comment]
非常感谢，输入时出错了。
