### ISSUE TITLE
关于LoongArch LP64的汇编代码如何编译出来？手头无该类设备的方法？

### ISSUE THREAD

**Issue by lingr7** [foxsen/archbase#29]
在第4章 软硬件协同的部分，关于c语言代码对应出的汇编代码 4.1.4本书85页。
我尝试了使用 https://godbolt.org/  发现这个比较流行的网站还没有支持LoongArch 相关的编译工具链。
相反的，这个网站已经支持了许多种编译工具链，包括x86 ，arm， RIsc-v相关的。
可能龙芯可以和这个网站团队合作一下，把LoongArch支持搞起来。

另外，手头没有实体采用LoongArch 的计算机，有无通过qemu模拟器的方法使用相关编译工具链。

**Comment by foxsen** [comment]
感谢您的建议。回头我们跟那个网站维护者联系下。
关于使用qemu的汇编环境，我做了一个供参考：https://github.com/foxsen/loongarch-assembly
也可以直接使用docker pull foxsen76/loongarch-assembly使用我做好的镜像。

**Comment by lingr7** [comment]
😂 我今天才发现这个网站，本身也是开源的，https://github.com/compiler-explorer/compiler-explorer ，要配置好本地编译器工具链，也可以对接出这个网站的web ui，希望龙芯官方能够做好支持。

**Comment by specialpointcentral** [comment]
> joy 我今天才发现这个网站，本身也是开源的，https://github.com/compiler-explorer/compiler-explorer ，要配置好本地编译器工具链，也可以对接出这个网站的web ui，希望龙芯官方能够做好支持。

您好，现在 https://godbolt.org/ 已经支持loongarch64了 (https://github.com/compiler-explorer/compiler-explorer/issues/4162)

**Comment by foxsen** [comment]
> > joy 我今天才发现这个网站，本身也是开源的，https://github.com/compiler-explorer/compiler-explorer ，要配置好本地编译器工具链，也可以对接出这个网站的web ui，希望龙芯官方能够做好支持。
> 
> 您好，现在 https://godbolt.org/ 已经支持loongarch64了 ([compiler-explorer/compiler-explorer#4162](https://github.com/compiler-explorer/compiler-explorer/issues/4162))

感谢！在大家的努力下，LoongArch的生态正在迅速发展。
