### ISSUE TITLE
【提案】PDF文档目录补充

### ISSUE THREAD

**Issue by Linkeer365** [foxsen/archbase#35]
foxsen您好，机械工业提供的 **精装电子版pdf** 没有书签目录（只有【文前】、【正文】两项），具体见

[本页-精装电子版-无书签](https://www.loongson.cn/pdf/computer.pdf)

![本页-精装电子版-无书签](https://user-images.githubusercontent.com/50709100/221777968-d8b87c56-57d4-4daf-9214-a0f9e296a522.png)

以及官网上面的，也没有书签，具体见

[官网-精装电子版-无书签](https://www.loongson.cn/kindeditor/attached/file/20220905/20220905064403_20930.pdf)

![官网-精装电子版-无书签](https://user-images.githubusercontent.com/50709100/221778557-c6a63132-45f4-4051-b5f6-17a9dcd9ccb6.png)

目前我想做的，就是给这个 **精装电子版** 加下目录书签，并且把 **有目录书签的版本更新到上述两个链接上** ，

以及，这个我处理完之后，需要跟谁联系更新呢。

---

**Comment by foxsen** [comment]
谢谢。不过我这里看生成的pdf都是有书签目录的？
![image](https://user-images.githubusercontent.com/875144/221767315-67c4e695-966c-49e9-932b-bb5bc0f8ad3c.png)

**Comment by Linkeer365** [comment]
> 谢谢。不过我这里看生成的pdf都是有书签目录的？ ![image](https://user-images.githubusercontent.com/875144/221767315-67c4e695-966c-49e9-932b-bb5bc0f8ad3c.png)

看错了，bookdown这一版是有书签目录的，我所说的是机械工业提供的另一版，上文表述已更新。

**Comment by foxsen** [comment]
好的，明白了。您修改好之后把pdf发我邮箱(fxzhang at ict.ac.cn)，我给相关人员更新。非常感谢！

**Comment by Linkeer365** [comment]
不用谢，单位这里没有windows机器，下班回去后会弄下，到时候发过去您接收下就行

**Comment by Linkeer365** [comment]
> 不用谢，单位这里没有windows机器，下班回去后会弄下，到时候发过去您接收下就行

不好意思有些迟了，您这边确认好之后，我就把这条issue关闭掉 💛

**Comment by Linkeer365** [comment]
谢谢foxsen 💛

**Comment by Linkeer365** [comment]
谢谢foxsen
