### ISSUE TITLE
请问在哪里可以找到配套的实验呢？

### ISSUE THREAD

**Issue by SpaceTime1999** [foxsen/archbase#36]
《计算机体系结构基础》非常赞！美中不足的就是自学者没有实验可以做，而没实验可以做的话，看完书只能留下浅浅的印象。
在自序中有提到将推出计算机体系结构实验平台和实验教材，请问是否有一个相对明确的时间点呢？
或者，如果想做相应的实验，是不是应该单独发邮件联系相关的负责人？

**Comment by foxsen** [comment]
目前在国科大上课配套的实验教材是

**Comment by foxsen** [comment]
本书还为高校教师配套全套教学课件及习题参考答案，请下载填写附件2：课程资源申请表发送至loongsonlab@loongson.cn联系获取相关资源。同时推荐使用《CPU设计实战》作为高校相关课程的配套实践教材。目前在与全国多位高校老师联合出LoongArch系列教材，其中包括教学平台和实验，大部分在今年下半年会完成。有了平台之后，这个教材的实验体系我们也会尽量早点推出，目前暂时无法给出确切时间。

**Comment by SpaceTime1999** [comment]
明白了，非常感谢！
