### ISSUE TITLE
关于第九章的插图 9.26

### ISSUE THREAD

**Issue by bLueriVerLHR** [foxsen/archbase#37]
https://github.com/foxsen/archbase/blob/887d5393f6e4cf38f6ffdb5e1698d8d121b0be60/19-pipeline.Rmd#L390
机械工业出版社提供的纸质书精排电子版上是 3A3000 的架构图，且图中右侧标识里也说明了是 3A3000 的架构图，个人认为这里笔误了。

**Comment by foxsen** [comment]
多谢指正，我们会修改。
