### ISSUE TITLE
10.1.1节存在笔误

### ISSUE THREAD

**Issue by tengwu** [foxsen/archbase#38]
https://github.com/foxsen/archbase/blob/6d46484305859edf8800c1a2a8810950da9fd5da/20-parallel-programming.Rmd#L15

这一段中可能存在笔误，寄存器重命名主要解决 **WAR** 和WAW的假相关问题，原文中写成了”寄存器重命名主要解决 **RAW** 和WAW的假相关问题“

**Comment by foxsen** [comment]
确实是的，谢谢指正。
