### ISSUE TITLE
1.3 节 计算机体系结构的发展 PDF版中渲染存在错误

### ISSUE THREAD

**Issue by bjrjk** [foxsen/archbase#5]
2. 工艺和计算机结构 中：
“更多” 指的是集成电路生产工艺在相同面积下提供了更多的晶体管来满足计算机体系结构
发展的需求。“更快” 指的是晶体管的开关速度不断提高，提高了计算机频率。“更省电” 指的是随
着工艺进步，工作电压降低，晶体管和连线的负载电容也降低，而功耗跟电压的平方成正比，跟
电容大小成正比。在0.13￿m 工艺之前，工艺每发展一代，电压就成比例下降，例如0.35￿m 工艺
的工作电压是3.3V，0.25￿m 工艺的工作电压是2.5V，0.18￿m 工艺的工作电压是1.8V，0.13￿m 工
艺的工作电压是1.2V。此外，随着线宽的缩小，晶体管和连线电容也相应变小。

其中所有关于微米的符号μ都没能显示出来。PDF中直接显示为0.13m。

后面还有一处：在0.13￿m 工艺之前，电压随线宽而线性下降。

**Comment by foxsen** [comment]
这个是字体的问题，原先除了flextable表格之外没有设置缺省字体，系统用了Latin Modern Roman(lmodern)，它没有定义某些希腊字母（除了μ之外，还有一些同样的问题）。解决的办法是统一设置缺省字体为Noto Sans CJK SC。
我不是太熟悉bookdown字体设置，目前是直接在latex preamble加了两行：
\usepackage{fontspec}
\setmainfont{Noto Sans CJK SC}
貌似在yml中设置mainfont应该能够直接让模板用该字体。
