### ISSUE TITLE
2.5.4 为什么不介绍LoongArch的特色？

### ISSUE THREAD

**Issue by cheungxi** [foxsen/archbase#6]
既然这本书主要介绍LoongArch，为什么反而不介绍其特色？难道是没有特色？

**Comment by foxsen** [comment]
好问题。这是从第二版继承下来的内容，没多想。大概是下意识觉得这个是给老家伙们的，LoongArch还太年轻:) 
我跟相关同事商量下，可以适当加点内容。LoongArch的兼容性考虑大概可以算一个特色，我们希望通过二进制扩展和软件配合，实现多种指令集的接近无损的翻译，最终可以达到“消灭指令集”或者说“软件定义指令集”的目标。为此还提了一整套融合型指令系统的设想。

**Comment by wlgemini** [comment]
棒，写书里吧，loongarch就要有loongarch的特色！
