### ISSUE TITLE
《计算机体系结构》《高级计算机体系结构》有相关repo，电子版吗？

### ISSUE THREAD

**Issue by Wanger-SJTU** [foxsen/archbase#7]

**Comment by foxsen** [comment]
还没来得及，目前只做完这本书。明年改版硕士的教材。

**Comment by XIJINIAN** [comment]
> 还没来得及，目前只做完这本书。明年改版硕士的教材。

太期待了，国内的基础教材越来越好！这本不逊色 Patt 那本《计算机系统概论》了，甚至附送一些知识hh，牛逼！
